version: "3.9"
services:
  sui:
    container_name: sui
    image: sui
    build:
      context: ./sui
      dockerfile: Dockerfile
    volumes:
      - ./sui/files/:/app/
    command: >
      sh -c "sui genesis && sui start"
    ports:
      - "9001:9001"
  aptos:
    container_name: aptos
    image: aptos
    build:
      context: ./aptos
      dockerfile: Dockerfile
    command: >
      aptos node run-local-testnet --with-faucet
    volumes:
      - ./aptos/files/:/app/
    ports:
      - "8080:8080"
      - "8081:8081"
  flow:
    container_name: flow
    image: flow
    build:
      context: ./flow
      dockerfile: Dockerfile
    volumes:
      - ./flow/files/:/app/
    ports:
      - "3569:3569"
      - "8888:8888"
  bal:
    container_name: bal
    image: bal
    build:
      context: ./bal
      dockerfile: Dockerfile
    volumes:
      - ./bal/files/:/app/files
    ports:
      - "9092:8080"
  bal_callback_handler:
    container_name: bal_callback_handler
    image: bal_callback_handler
    build:
      context: ./bal_callback_handler
      dockerfile: Dockerfile
    ports:
      - "5010:5010"
